### ISSUE TITLE
ESM Template

### ISSUE THREAD

**Issue by mgrubinger** [colyseus/create-colyseus-app#12]
Hi! 
I want to suggest including branch using the ES Modules syntax instead of CommonJS. 
Since Node 13.2 Node officially supports ESM, so there might be more users (like me) who would prefer this syntax.
I already got everything running so I could create a PR with the ESM version of the template files.
This could be another option in the create-colyseus-app script: Typescript, JavaScript (CommonJS) , JavaScript (ESM), Haxe

What do you think?

Thanks, 
Martin

**Comment by endel** [comment]
Hi Martin! That'd be an interesting addition! A pull request would be much appreciated! Cheers!

**Comment by mgrubinger** [comment]
Will do :)

**Comment by endel** [comment]
Thank you @mgrubinger, I've taken what you started and added an ESM template here!

**Comment by mgrubinger** [comment]
Thank you!! I had the PR sitting half-finished but was just too busy, sorry.
