### ISSUE TITLE
Strange files generated

### ISSUE THREAD

**Issue by Chnapy** [colyseus/create-colyseus-app#6]
Hi :wave: 

When I generated my project, with `npm init colyseus-app` I got a lot of strange files:
![image](https://user-images.githubusercontent.com/7474483/71942600-083d3e00-31be-11ea-92cf-7b9f13d1cd45.png)

It seems to be all scripts, I don't know what for, I didn't read anything of them on the readme :question: 
Thanks for any help :+1:

**Comment by endel** [comment]
This looks very strange indeed, are you using Windows? Did you run `npm init colyseus-app` via powershell?

Thanks for reporting!

**Comment by Chnapy** [comment]
Thanks for your quick answer!
I'm on Windows 7. I used the bash of Git GUI.
Well, I understand by your answer I can delete all of them :smile: 

For help, the generated project (w/o node_modules):
[colyseus-app.zip](https://github.com/colyseus/create-colyseus-app/files/4033254/colyseus-app.zip)

**Comment by innocenzi** [comment]
I can confirm this is happening on Windows. I think those should be generated in `node_modules/bin`, but somehow they're being generated in the root.

**Comment by jcjveraa** [comment]
Hi Endel, indeed same behavior here - using NPM 6.14.3, Windows Powershell in up-to-date VS Code.
"Solved" by simply cloning [the TypeScript repository](https://github.com/colyseus/create-colyseus-app/tree/typescript) and `npm install`-ing after that.

This results in the files reported above being generated in ./node_modules/.bin as was expected by hawezo above.

**Comment by davidhernandeze** [comment]
it happen to me when I tried `npm init colyseus-app .` I solved running `npm init colyseus-app ./my-colyseus-app` instead
