### ISSUE TITLE
npm using default init behaviour when running the init colyseus-app command

### ISSUE THREAD

**Issue by wpower12** [colyseus/create-colyseus-app#7]
I've installed the init template with npm install -g create-colyseus-app, and then went on to try and do the init as suggested, but always get the basic init behaviour, not the script asking if i'd like type script etc...

**Comment by endel** [comment]
hi @wpower12, which version of NPM you have installed?

this doesn't work for you? `npm init colyseus-app`

here's my output:

```
 $ npm --version
6.9.0
 $ npm init colyseus-app ./my-colyseus-app
npx: installed 15 in 3.964s
? Which language you'd like to use? …
❯ TypeScript (recommended)
  JavaScript
  Haxe
```

**Comment by wpower12** [comment]
Yea just realized I have a borked npm install. One as root and one local. Fixing now. Sorry for the fud.
