### ISSUE TITLE
The room never creates

### ISSUE THREAD

**Issue by davidhernandeze** [colyseus/create-colyseus-app#8]
Hi, I installed this example server, and add a simple
 `onCreate (options: any) {
    console.log('room created')
  }`
on MyRoom.
The server starts without problem and shows `Listening on ws://localhost:2568`, but it never outputs "room created".
I'm running node v12.13 on windows 10

**Comment by endel** [comment]
@davidhernandeze rooms get created only when the client requests to, via `client.create()` or `client.joinOrCreate()`, the server does not create them automatically.

**Comment by davidhernandeze** [comment]
Thanks a lot @endel
